# Generated by Django 3.2.7 on 2021-10-10 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
