# Generated by Django 3.2.7 on 2021-10-10 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_article_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='json',
            field=models.JSONField(blank=True, default={'history': 'true'}, null=True),
        ),
    ]
